version: '3'
services:

  gerenciador-atas_webapp:
    build:
      context: .
      dockerfile: Dockerfile-gerenciador-atas_webapp
    environment:
      - TZ=America/Fortaleza
    image: dv-gerenciador-atas-webapp:v1.0
    ports:
            - "10201:80"
    container_name: dv-gerenciador-atas-webapp
    hostname: dv-gerenciador-atas-webapp
    networks:
      - gerenciador-atas-net-dv
    volumes:
      - ./aplicacoes/gerenciador_atas/:/home/app/webapp/
      - ./.app-config/database-gerenciador-atas.yml:/home/app/webapp/config/database.yml

networks:
  gerenciador-atas-net-dv:
    driver: bridge
